services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    ports:
      - "5700:3000"
    environment:
      # Coolify will provide FQDN for external access
      - SERVICE_FQDN_METABASE
      # Database configuration - using Coolify variables
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=${POSTGRES_DATABASE:-metabase}
      - MB_DB_PORT=5432
      - MB_DB_USER=${POSTGRES_USER:-metabase}
      - MB_DB_PASS=${SERVICE_PASSWORD_POSTGRES}
      - MB_DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s
    volumes:
      - metabase-data:/plugins
    labels:
      - coolify.managed=true

  postgres:
    image: postgres:15-alpine
    container_name: metabase_postgres
    restart: unless-stopped
    ports:
      - "5710:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-metabase}
      - POSTGRES_USER=${POSTGRES_USER:-metabase}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      - coolify.managed=true

volumes:
  metabase-data:
    driver: local
  postgres-data:
    driver: local

networks:
  default:
    name: metabase-network