#!/bin/bash

echo "🔧 Fixing PostgreSQL Port Mapping Issue"
echo "======================================="

API_TOKEN="5|0IZMg4cQaIGgoBdeHN5x27idlmwFN0OQbA4XONAD84f15f59"
COOLIFY_URL="https://coolify.timothynguyen.work"
POSTGRES_UUID="tkc0s408ws00ckc4o88swc0s"

echo "🔍 Current Issue:"
echo "   ✅ PostgreSQL service: running:healthy in Coolify"
echo "   ❌ Port 5710: Not exposed to host system"
echo "   ❌ Metabase: Can't connect to 91.99.53.200:5710"
echo ""

echo "🚨 ROOT CAUSE IDENTIFIED:"
echo "   The PostgreSQL service doesn't have port mappings configured!"
echo "   Service shows 'ports: null' in API response"
echo ""

echo "📊 Current service status:"
curl -s -H "Authorization: Bearer $API_TOKEN" \
    "$COOLIFY_URL/api/v1/services/$POSTGRES_UUID" | \
    jq '{name, status, ports}'

echo ""
echo "🔧 MANUAL FIX REQUIRED:"
echo "========================================"
echo ""
echo "The PostgreSQL service needs to be reconfigured with proper port mapping."
echo "Here are your options:"
echo ""
echo "OPTION 1: Fix PostgreSQL Service Port Mapping"
echo "--------------------------------------------"
echo "1. Go to: https://coolify.timothynguyen.work"
echo "2. Navigate to: Services → metabase-db"
echo "3. Go to Configuration/Advanced settings"
echo "4. Look for port mappings and add: 5710:5432"
echo "5. Save and restart the service"
echo ""
echo "OPTION 2: Create New PostgreSQL Service (Recommended)"
echo "-----------------------------------------------------"
echo "1. Delete current metabase-db service"
echo "2. Create new PostgreSQL service with correct port mapping"
echo "3. Configure with same credentials"
echo ""
echo "OPTION 3: Use Internal Docker Networking"
echo "----------------------------------------"
echo "Change Metabase environment variables back to:"
echo "   MB_DB_HOST=metabase-db-tkc0s408ws00ckc4o88swc0s"
echo "   MB_DB_PORT=5432"
echo ""
echo "🎯 QUICKEST SOLUTION - Try Option 3 First:"
echo "=========================================="
echo "Go to Coolify Dashboard:"
echo "Applications → metabase-app → Environment Variables"
echo ""
echo "Change back to internal networking:"
echo "   MB_DB_HOST = metabase-db-tkc0s408ws00ckc4o88swc0s"
echo "   MB_DB_PORT = 5432"
echo ""
echo "Then Save → Deploy"
echo ""
echo "💡 This uses Docker's internal networking instead of host ports"
echo ""
echo "🔄 Test after any changes:"
echo "   ./VERIFY_APPLICATION.sh"
echo ""
echo "If Option 3 doesn't work, we'll need to fix the PostgreSQL service port mapping."